name: 'build'

on:
  push:
    branches: 
      - $default-branch
      - main
      - feature/*
      - hotfix/*
  pull_request: {}
  workflow_call: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011
        with:
          extra_nix_config: 'access-tokens = github.com=${{ github.token }}'

      - name: Build tarball
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin run .#nixosConfigurations.nixos.config.system.build.tarballBuilder

      - name: Upload tarball
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: nixos-wsl-starter
          path: nixos-wsl.tar.gz
