name: 'build'

on:
  push:
    branches: 
      - $default-branch
      - main
      - feature/*
      - hotfix/*
  pull_request: {}
  workflow_call: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true

      - uses: cachix/install-nix-action@ba01fffc512be2cf5d4dce85159f0e40621f84ec
        with:
          extra_nix_config: 'access-tokens = github.com=${{ github.token }}'

      - name: Build tarball
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin run .#nixosConfigurations.nixos.config.system.build.tarballBuilder

      - name: Upload tarball
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: nixos-wsl.tar.gz
          path: nixos-wsl.tar.gz
